name = "kaapav-app"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
WEBHOOK_VERIFY_TOKEN = "kaapav_verify_2024"
APP_URL = "https://app.kaapav.com"
WEBSITE_URL = "https://www.kaapav.com"
CATALOG_URL = "https://wa.me/c/919148330016"
WAME_CHAT_URL = "https://wa.me/919148330016"
BESTSELLERS_URL = "https://www.kaapav.com/shop/category/bestsellers"
PAYMENT_URL = "https://razorpay.me/@kaapav"
TRACKING_URL = "https://www.shiprocket.in/shipment-tracking/"
FACEBOOK_URL = "https://www.facebook.com/kaapavfashionjewellery/"
INSTAGRAM_URL = "https://www.instagram.com/kaapavfashionjewellery/"

[[d1_databases]]
binding = "DB"
database_name = "kaapav-db"
database_id = "236ccd98-28d1-424c-a5c3-761e35869992"

[[kv_namespaces]]
binding = "KV"
id = "2a8a79955860411eb62e216399ef4fc0"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "kaapav-media"

[triggers]
crons = ["*/5 * * * *"]

routes = [
  { pattern = "wa.kaapav.com/*", zone_name = "kaapav.com" }
]